/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import entidades.Alumno;
import entidades.Asistencia;
import entidades.Curso;
import entidades.Turno;

/**
 *
 * @author USER
 */
public class JFrameRegistroDeAsistencia extends javax.swing.JFrame {

    private JFrameListaAsistencia padre;
    private Asistencia asistencia;
    private boolean editar = false;

    private Alumno alumnoSeleccionado;
    private Curso cursoSeleccionado;
    private Turno turnoSeleccionado;

    /**
     * Creates new form RegistroDeAsistencia
     */
    public JFrameRegistroDeAsistencia(JFrameListaAsistencia padre) {
        initComponents();
        this.padre = padre;
        cbTurno.removeAll();
        cbTurno.setEnabled(false);
    }

    public JFrameRegistroDeAsistencia(JFrameListaAsistencia padre,
            Asistencia asistencia) {
        initComponents();
        this.padre = padre;
        this.asistencia = asistencia;
        this.editar = true;
        this.btnAgregar.setVisible(false);
        this.btnBuscarAlumno.setVisible(false);
        this.btnBuscarCurso.setVisible(false);
        lblTitulo.setText("Alumno");
        this.txtNombreAlumno.setText(asistencia.getAlumno().getMostrarNombre());
        this.txtApellidoAlumno.setText(asistencia.getAlumno().
                getMostrarApellido());
        this.txtCodigoAlumno.setText(asistencia.getAlumno().getMostrarCodigo());
        this.txtAsistenciaAlumno.setText(asistencia.getAlumno().
                getMostrarAsistenciaAlumno());
        this.txtCurso.setText(asistencia.getCurso().getMostrarCurso());
        cbTurno.removeAll();
        cbTurno.addItem(asistencia.getTurno().getNombre());
    }

    //Métodos
    private void salir() {
        padre.setVisible(true);
        this.dispose();
    }

    public void guardarAsistencia() {
        if (alumnoSeleccionado != null && cursoSeleccionado != null
                && turnoSeleccionado != null) {
            int seleccion = cbTurno.getSelectedIndex();
            turnoSeleccionado = cursoSeleccionado.getTurnos().get(seleccion);
            asistencia = new Asistencia(alumnoSeleccionado, cursoSeleccionado,
                    turnoSeleccionado);
            this.padre.agregarAsistencia(asistencia);
        }
    }

    public void setAlumno(Alumno alumno) {
        this.alumnoSeleccionado = alumno;
        txtNombreAlumno.setText(alumno.getMostrarNombre());
        this.alumnoSeleccionado = alumno;
        txtApellidoAlumno.setText(alumno.getMostrarApellido());
        this.alumnoSeleccionado = alumno;
        txtCodigoAlumno.setText(alumno.getMostrarCodigo());
        this.alumnoSeleccionado = alumno;
        txtAsistenciaAlumno.setText(alumno.getMostrarAsistenciaAlumno());
    }

    public void setCurso(Curso curso) {
        this.cursoSeleccionado = curso;
        txtCurso.setText(this.cursoSeleccionado.getMostrarCurso());

        cbTurno.removeAll();
        for (Turno turn : curso.getTurnos()) {
            cbTurno.addItem(turn.getNombre());
        }
        cbTurno.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        txtCurso = new javax.swing.JTextField();
        txtApellidoAlumno = new javax.swing.JTextField();
        cbTurno = new javax.swing.JComboBox<>();
        txtCodigoAlumno = new javax.swing.JTextField();
        txtAsistenciaAlumno = new javax.swing.JTextField();
        btnBuscarCurso = new javax.swing.JButton();
        btnBuscarAlumno = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTitulo.setText("Registro de Asistencia");

        cbTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTurno.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbTurnoPropertyChange(evt);
            }
        });

        btnBuscarCurso.setBackground(new java.awt.Color(0, 102, 102));
        btnBuscarCurso.setText("Buscar Curso");
        btnBuscarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCursoActionPerformed(evt);
            }
        });

        btnBuscarAlumno.setBackground(new java.awt.Color(0, 102, 102));
        btnBuscarAlumno.setText("Buscar Alumno");
        btnBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlumnoActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(0, 153, 51));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAgregar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblTitulo)
                                .addComponent(txtNombreAlumno)
                                .addComponent(txtApellidoAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                .addComponent(txtCodigoAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                .addComponent(txtAsistenciaAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                            .addGap(33, 33, 33)
                            .addComponent(btnBuscarAlumno)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCurso)
                            .addComponent(cbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(btnBuscarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAlumno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCodigoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAsistenciaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnSalir))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        salir();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbTurnoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbTurnoPropertyChange
        if (this.cursoSeleccionado != null) {
            Turno turn = this.cursoSeleccionado.getTurnos().
                    get(cbTurno.getSelectedIndex());
            turnoSeleccionado = turn;
        }
    }//GEN-LAST:event_cbTurnoPropertyChange

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        guardarAsistencia();
        salir();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoActionPerformed
        JFrameListaAlumnos pantallaAlumnos = new JFrameListaAlumnos(this);
        pantallaAlumnos.setLocationRelativeTo(this);
        pantallaAlumnos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBuscarAlumnoActionPerformed

    private void btnBuscarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCursoActionPerformed
        JFrameListaCursos pantallaCursos = new JFrameListaCursos(this);
        pantallaCursos.setLocationRelativeTo(this);
        pantallaCursos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBuscarCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistroDeAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistroDeAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistroDeAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistroDeAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameRegistroDeAsistencia(new JFrameListaAsistencia()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarAlumno;
    private javax.swing.JButton btnBuscarCurso;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbTurno;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApellidoAlumno;
    private javax.swing.JTextField txtAsistenciaAlumno;
    private javax.swing.JTextField txtCodigoAlumno;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtNombreAlumno;
    // End of variables declaration//GEN-END:variables
}
